/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package prueba;

import java.util.Scanner;

/**
 *
 * @author windows
 */
public class JFrame extends javax.swing.JFrame {

    /**
     * Creates new form JFrame
     */
    public JFrame() {
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        panel1 = new javax.swing.JPanel();
        rbtn1 = new javax.swing.JRadioButton();
        rbtn2 = new javax.swing.JRadioButton();
        rbtn3 = new javax.swing.JRadioButton();
        newtonPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        newtonPanel2 = new javax.swing.JPanel();
        txtMasa = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtAceleracion = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtResultado = new javax.swing.JTextArea();
        btnCalcular = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        newtonPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        panel2 = new javax.swing.JPanel();
        rbtn11 = new javax.swing.JRadioButton();
        rbtn22 = new javax.swing.JRadioButton();
        rbtn33 = new javax.swing.JRadioButton();
        trabajoPanel = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txtFuerza = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        txtDistancia = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtResultadoT = new javax.swing.JTextArea();
        btnCalcularT = new javax.swing.JButton();
        btnNuevoT = new javax.swing.JButton();
        energiaPanel = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        potenciaPanel = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        panel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.setPreferredSize(new java.awt.Dimension(2761, 496));

        panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonGroup1.add(rbtn1);
        rbtn1.setText("Ley de Inercia");
        rbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn1ActionPerformed(evt);
            }
        });
        panel1.add(rbtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 40, -1, -1));

        buttonGroup1.add(rbtn2);
        rbtn2.setText("Ley Fundamental de la Dinamica");
        rbtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn2ActionPerformed(evt);
            }
        });
        panel1.add(rbtn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 82, -1, -1));

        buttonGroup1.add(rbtn3);
        rbtn3.setText("Principio de Acción y Reacción");
        rbtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn3ActionPerformed(evt);
            }
        });
        panel1.add(rbtn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 125, -1, -1));

        newtonPanel1.setBackground(new java.awt.Color(255, 255, 204));

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel4.setText("La ley de la inercia o primera ley postula que un cuerpo permanecerá en reposo");

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel6.setText("o en movimiento recto con una velocidad constante, a menos que se aplique una");

        jLabel7.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel7.setText("fuerza externa.");

        jLabel8.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel8.setText("La fórmula de la primera ley de Newton es:  ");

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/formula1.jpg"))); // NOI18N

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ley1.jpg"))); // NOI18N

        javax.swing.GroupLayout newtonPanel1Layout = new javax.swing.GroupLayout(newtonPanel1);
        newtonPanel1.setLayout(newtonPanel1Layout);
        newtonPanel1Layout.setHorizontalGroup(
            newtonPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newtonPanel1Layout.createSequentialGroup()
                .addGroup(newtonPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(newtonPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(newtonPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addGroup(newtonPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel9))))
                    .addGroup(newtonPanel1Layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(jLabel10)))
                .addContainerGap(112, Short.MAX_VALUE))
        );
        newtonPanel1Layout.setVerticalGroup(
            newtonPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newtonPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(newtonPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(newtonPanel1Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel8))
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addContainerGap(96, Short.MAX_VALUE))
        );

        panel1.add(newtonPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(258, 40, 606, -1));

        newtonPanel2.setBackground(new java.awt.Color(153, 255, 255));

        jLabel17.setText("Ingrese la masa (m)");

        jLabel18.setText("Ingrese la aceleracion (a)");

        txtResultado.setColumns(20);
        txtResultado.setRows(5);
        jScrollPane1.setViewportView(txtResultado);

        btnCalcular.setText("calcular");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        btnNuevo.setText("nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout newtonPanel2Layout = new javax.swing.GroupLayout(newtonPanel2);
        newtonPanel2.setLayout(newtonPanel2Layout);
        newtonPanel2Layout.setHorizontalGroup(
            newtonPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newtonPanel2Layout.createSequentialGroup()
                .addGroup(newtonPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(newtonPanel2Layout.createSequentialGroup()
                        .addGap(239, 239, 239)
                        .addGroup(newtonPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(newtonPanel2Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(newtonPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel18)
                                    .addGroup(newtonPanel2Layout.createSequentialGroup()
                                        .addGap(9, 9, 9)
                                        .addComponent(jLabel17))))
                            .addComponent(txtMasa)
                            .addComponent(txtAceleracion)))
                    .addGroup(newtonPanel2Layout.createSequentialGroup()
                        .addGap(199, 199, 199)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addGroup(newtonPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnNuevo)
                            .addComponent(btnCalcular))))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        newtonPanel2Layout.setVerticalGroup(
            newtonPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newtonPanel2Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(txtMasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17)
                .addGap(34, 34, 34)
                .addComponent(txtAceleracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addGroup(newtonPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, newtonPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, newtonPanel2Layout.createSequentialGroup()
                        .addComponent(btnCalcular)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnNuevo)
                        .addGap(73, 73, 73))))
        );

        panel1.add(newtonPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(258, 41, 600, 400));

        newtonPanel3.setBackground(new java.awt.Color(255, 204, 204));

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel1.setText("La tercera ley de Newton dice que toda acción genera una reacción igual, pero en sentido opuesto.");
        jLabel1.setToolTipText("");

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel3.setText("La fórmula de ley de acción y reacción es:");
        jLabel3.setToolTipText("");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/formula3.jpg"))); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ley3.jpg"))); // NOI18N

        javax.swing.GroupLayout newtonPanel3Layout = new javax.swing.GroupLayout(newtonPanel3);
        newtonPanel3.setLayout(newtonPanel3Layout);
        newtonPanel3Layout.setHorizontalGroup(
            newtonPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newtonPanel3Layout.createSequentialGroup()
                .addGroup(newtonPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(newtonPanel3Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2))
                    .addGroup(newtonPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(newtonPanel3Layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(jLabel5)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        newtonPanel3Layout.setVerticalGroup(
            newtonPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newtonPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(newtonPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(newtonPanel3Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel3))
                    .addGroup(newtonPanel3Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel2)))
                .addGap(90, 90, 90)
                .addComponent(jLabel5)
                .addContainerGap(133, Short.MAX_VALUE))
        );

        panel1.add(newtonPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(264, 40, 600, 450));

        jTabbedPane1.addTab("Leyes de Newton", panel1);

        panel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonGroup2.add(rbtn11);
        rbtn11.setText("Trabajo");
        rbtn11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn11ActionPerformed(evt);
            }
        });
        panel2.add(rbtn11, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 41, -1, -1));

        buttonGroup2.add(rbtn22);
        rbtn22.setText("Energia");
        rbtn22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn22ActionPerformed(evt);
            }
        });
        panel2.add(rbtn22, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 79, -1, -1));

        buttonGroup2.add(rbtn33);
        rbtn33.setText("Potencia");
        rbtn33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn33ActionPerformed(evt);
            }
        });
        panel2.add(rbtn33, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 117, -1, -1));

        trabajoPanel.setBackground(new java.awt.Color(204, 255, 255));

        jLabel13.setText("¿Qué requiere más trabajo: subir un bulto de 420 N a una colina de 200 metros de altura, o un bulto de 210 N a una ");

        jLabel19.setText("colina de 400 metros de altura? (no consideramos el ángulo de aplicación de la fuerza, que para ambos caso el mismo).");

        jLabel20.setText("Apliquemos la fórmula simple:");

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/formula-trabajo.jpg"))); // NOI18N

        jLabel22.setText("Ingrese la fuerza (F)");

        jLabel23.setText("Ingrese la distancia (d)");

        txtResultadoT.setColumns(20);
        txtResultadoT.setRows(5);
        jScrollPane2.setViewportView(txtResultadoT);

        btnCalcularT.setText("calcular");
        btnCalcularT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularTActionPerformed(evt);
            }
        });

        btnNuevoT.setText("nuevo");

        javax.swing.GroupLayout trabajoPanelLayout = new javax.swing.GroupLayout(trabajoPanel);
        trabajoPanel.setLayout(trabajoPanelLayout);
        trabajoPanelLayout.setHorizontalGroup(
            trabajoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(trabajoPanelLayout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(trabajoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCalcularT)
                    .addComponent(btnNuevoT))
                .addGap(70, 70, 70))
            .addGroup(trabajoPanelLayout.createSequentialGroup()
                .addGroup(trabajoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(trabajoPanelLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(trabajoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addComponent(jLabel13)))
                    .addGroup(trabajoPanelLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel20)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel21))
                    .addGroup(trabajoPanelLayout.createSequentialGroup()
                        .addGap(250, 250, 250)
                        .addGroup(trabajoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(trabajoPanelLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel22))
                            .addComponent(txtDistancia, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                            .addComponent(txtFuerza)
                            .addComponent(jLabel23))))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        trabajoPanelLayout.setVerticalGroup(
            trabajoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(trabajoPanelLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel19)
                .addGroup(trabajoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(trabajoPanelLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel20))
                    .addGroup(trabajoPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel21)))
                .addGap(27, 27, 27)
                .addComponent(txtFuerza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(trabajoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(trabajoPanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel22)
                        .addGap(18, 18, 18)
                        .addComponent(txtDistancia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel23)
                        .addGap(33, 33, 33)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(62, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, trabajoPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCalcularT)
                        .addGap(18, 18, 18)
                        .addComponent(btnNuevoT)
                        .addGap(73, 73, 73))))
        );

        panel2.add(trabajoPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 670, 460));

        energiaPanel.setBackground(new java.awt.Color(204, 255, 204));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/formulas-energia.jpg"))); // NOI18N

        jLabel28.setText("Formulas:");

        jLabel29.setText("La energía se describiría como la capacidad de Pedro Castillo para llevar a cabo el trabajo. ");

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/energia.jpg"))); // NOI18N

        javax.swing.GroupLayout energiaPanelLayout = new javax.swing.GroupLayout(energiaPanel);
        energiaPanel.setLayout(energiaPanelLayout);
        energiaPanelLayout.setHorizontalGroup(
            energiaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(energiaPanelLayout.createSequentialGroup()
                .addGroup(energiaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(energiaPanelLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel29))
                    .addGroup(energiaPanelLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel28)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel15)))
                .addContainerGap(161, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, energiaPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel30)
                .addGap(101, 101, 101))
        );
        energiaPanelLayout.setVerticalGroup(
            energiaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(energiaPanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel29)
                .addGroup(energiaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(energiaPanelLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel28))
                    .addGroup(energiaPanelLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel15)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel30)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        panel2.add(energiaPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 670, 460));

        potenciaPanel.setBackground(new java.awt.Color(255, 153, 153));

        jLabel16.setText("En la vida, lo importante es la realización del trabajo, pero también el tiempo durante el cual se realiza el trabajo.");

        jLabel24.setText("La relación entre el trabajo y el intervalo de tiempo durante el cual se realiza este trabajo se denomina potencia.");

        jLabel25.setText("Formula:");

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/formula-potencia.jpg"))); // NOI18N

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/trabajo1.jpg"))); // NOI18N

        javax.swing.GroupLayout potenciaPanelLayout = new javax.swing.GroupLayout(potenciaPanel);
        potenciaPanel.setLayout(potenciaPanelLayout);
        potenciaPanelLayout.setHorizontalGroup(
            potenciaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(potenciaPanelLayout.createSequentialGroup()
                .addGroup(potenciaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(potenciaPanelLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(potenciaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel24)
                            .addComponent(jLabel16)))
                    .addGroup(potenciaPanelLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel26)))
                .addContainerGap(67, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, potenciaPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel27)
                .addGap(159, 159, 159))
        );
        potenciaPanelLayout.setVerticalGroup(
            potenciaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(potenciaPanelLayout.createSequentialGroup()
                .addGroup(potenciaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(potenciaPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel26))
                    .addGroup(potenciaPanelLayout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(jLabel25)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel27)
                .addContainerGap(95, Short.MAX_VALUE))
        );

        panel2.add(potenciaPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 670, 460));

        jTabbedPane1.addTab("Trabajo Energia y Potencia", panel2);

        jLabel11.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel11.setText("Podemos decir que el peso y la fuerza elástica son fuerzas conservativas, si sobre un cuerpo actúan otras fuerzas");

        jLabel12.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel12.setText("que desarrollan trabajo, la energía mecánica no se conserva.  ");

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/tra-ener.jpg"))); // NOI18N

        javax.swing.GroupLayout panel3Layout = new javax.swing.GroupLayout(panel3);
        panel3.setLayout(panel3Layout);
        panel3Layout.setHorizontalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel3Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addGroup(panel3Layout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(190, Short.MAX_VALUE))
        );
        panel3Layout.setVerticalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel3Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addGap(51, 51, 51)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(88, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Teorema Trabajo y Energia", panel3);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 870, 484));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtn1ActionPerformed
        // TODO add your handling code here:
        if(rbtn1.isSelected()==true){
            newtonPanel1.setVisible(true);
            }
    
        if(rbtn2.isSelected()==false){
            newtonPanel2.setVisible(false);
            }
        
        if(rbtn3.isSelected()==false){
            newtonPanel3.setVisible(false);
            }
    }//GEN-LAST:event_rbtn1ActionPerformed

    private void rbtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtn2ActionPerformed
        // TODO add your handling code here:
        if(rbtn1.isSelected()==false){
            newtonPanel1.setVisible(false);
            }
    
        if(rbtn2.isSelected()==true){
            newtonPanel2.setVisible(true);
            }
        
        if(rbtn3.isSelected()==false){
            newtonPanel3.setVisible(false);
            }
    }//GEN-LAST:event_rbtn2ActionPerformed

    private void rbtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtn3ActionPerformed
        // TODO add your handling code here:
        if(rbtn1.isSelected()==false){
            newtonPanel1.setVisible(false);
            }
    
        if(rbtn2.isSelected()==false){
            newtonPanel2.setVisible(false);
            }
        
        if(rbtn3.isSelected()==true){
            newtonPanel3.setVisible(true);
            }
    }//GEN-LAST:event_rbtn3ActionPerformed

    private void rbtn11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtn11ActionPerformed
        // TODO add your handling code here:
        if(rbtn11.isSelected()==true){
            trabajoPanel.setVisible(true);
            }
    
        if(rbtn22.isSelected()==false){
            energiaPanel.setVisible(false);
            }
        
        if(rbtn33.isSelected()==false){
            potenciaPanel.setVisible(false);
            }
    }//GEN-LAST:event_rbtn11ActionPerformed

    private void rbtn22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtn22ActionPerformed
        // TODO add your handling code here:
        if(rbtn11.isSelected()==false){
            trabajoPanel.setVisible(false);
            }
    
        if(rbtn22.isSelected()==true){
            energiaPanel.setVisible(true);
            }
        
        if(rbtn33.isSelected()==false){
            potenciaPanel.setVisible(false);
            }
    }//GEN-LAST:event_rbtn22ActionPerformed

    private void rbtn33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtn33ActionPerformed
        // TODO add your handling code here:
        if(rbtn11.isSelected()==false){
            trabajoPanel.setVisible(false);
            }
    
        if(rbtn22.isSelected()==false){
            energiaPanel.setVisible(false);
            }
        
        if(rbtn33.isSelected()==true){
            potenciaPanel.setVisible(true);
            }
    }//GEN-LAST:event_rbtn33ActionPerformed

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        // TODO add your handling code here:
        boolean fuerza = true;
        int m=Integer.parseInt(txtMasa.getText());
        int a=Integer.parseInt(txtAceleracion.getText());
        
        
        Scanner scn=new Scanner(System.in);
    
        if(fuerza){
            
            int x=(m*a) ;
            txtResultado.append("La fuerza es " +x+ " N");
           
        }
    }//GEN-LAST:event_btnCalcularActionPerformed

    private void btnCalcularTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularTActionPerformed
        // TODO add your handling code here:
        boolean trabajo = true;
        int F=Integer.parseInt(txtFuerza.getText());
        int d=Integer.parseInt(txtDistancia.getText());
        
        
        Scanner scn=new Scanner(System.in);
    
        if(trabajo){
            
            int x=(F*d) ;
            txtResultadoT.append("El trabajo es " +x+ " J");
           
        }
    }//GEN-LAST:event_btnCalcularTActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        // TODO add your handling code here:
        txtMasa.setText("");
        txtAceleracion.setText("");
        txtResultado.setText("");
    }//GEN-LAST:event_btnNuevoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnCalcularT;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnNuevoT;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JPanel energiaPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel newtonPanel1;
    private javax.swing.JPanel newtonPanel2;
    private javax.swing.JPanel newtonPanel3;
    private javax.swing.JPanel panel1;
    private javax.swing.JPanel panel2;
    private javax.swing.JPanel panel3;
    private javax.swing.JPanel potenciaPanel;
    private javax.swing.JRadioButton rbtn1;
    private javax.swing.JRadioButton rbtn11;
    private javax.swing.JRadioButton rbtn2;
    private javax.swing.JRadioButton rbtn22;
    private javax.swing.JRadioButton rbtn3;
    private javax.swing.JRadioButton rbtn33;
    private javax.swing.JPanel trabajoPanel;
    private javax.swing.JTextField txtAceleracion;
    private javax.swing.JTextField txtDistancia;
    private javax.swing.JTextField txtFuerza;
    private javax.swing.JTextField txtMasa;
    private javax.swing.JTextArea txtResultado;
    private javax.swing.JTextArea txtResultadoT;
    // End of variables declaration//GEN-END:variables
}
